project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Franziska Pradel"
  site-url: "https://www.franziskapradel.com"
  favicon: favicon.jpg
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.pdf
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/franziska-pradel-1a30347a/"
      - icon: envelope
        href: "mailto:franziska.pradel@tum.de"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true