---
title: "Publications"
---

## Work in Progress

*These papers are currently under review or in advanced preparation.*

-   **Gender Differences in Demanding Moderation** (with Y. Theocharis & S. Kosmidis) \[[Preprint](https://osf.io/preprints/osf/aw6tk_v1)\]

-   **Mapping Elite Interconnections: Using Wikidata and Wikipedia for Social Network Analysis** (with D. Tisch) *Conditional Accept in Soziale Welt (Special Issue on Computational Social Science)*.

-   **Systemic Toxicity Inference Drives Discourse Withdrawal Across 10 Democracies** (with F. Quint & Y. Theocharis)

------------------------------------------------------------------------

## Peer-Reviewed Articles

**2025**

-   **Influence of Hate Speech About Refugees in Search Algorithms on Political Attitudes** *New Media & Society*, 27(8), 4865-4890. \[[PDF](Pradel_2024_Influence-of-hate-speech-about-refugees.pdf)\] \| \[[DOI](https://doi.org/10.1177/14614448241244735)\]

-   **Content Warning: Public Attitudes on Content Moderation and Freedom of Expression** (with Y. Theocharis, S. Kosmidis, J. Zilinsky, F. Quint) *TUM Think Tank*. \[[PDF](Content_Warnng_Public_Attitudes_on_Moderation_and_Freedom_of_Expression.pdf)\]

**2024**

-   **Toxic Speech and Limited Demand for Content Moderation on Social Media** (with J. Zilinsky, S. Kosmidis, Y. Theocharis) *American Political Science Review*, 118(4), 1895-1912. \[[PDF](Pradel_et_al_2024_toxic-speech.pdf)\] \| \[[DOI](https://doi.org/10.1017/S000305542300134X)\]

-   **Justifying an Invasion: When is Disinformation Successful?** (with J. Zilinsky, Y. Theocharis, et al.) *Political Communication*, 41(6), 965-986. \[[PDF](Zilinsky_Theocharis_Pradel_et_al_Justifying%20an%20Invasion.pdf)\] \| \[[DOI](https://doi.org/10.1080/10584609.2024.2352483)\]

-   **Dynamics in Search Engine Query Suggestions for European Politicians** (with F. Haak, S.-O. Proksch, P. Schaer) *Proceedings of the 10th ACM Conference on Web Science*. \[[PDF](Pradel_Haak_Schaer_Proksch_Dynamics_in_Search_Engine_Suggestions.pdf)\] \| \[[DOI](https://doi.org/10.1145/3614419.3644006)\]

-   **Beliefs in Conspiracy Theories and Online News Consumption** (with S. Jin, J. Zilinsky, Y. Theocharis) *Journal of Quantitative Description: Digital Media*, 4. \[[PDF](Jin_Zilinksy_Pradel_Theocharis_Conspiracy_Theories_COVID.pdf)\] \| \[[DOI](https://doi.org/10.51685/jqd.2024.008)\]

-   **Health Consequences of a Death Threat: How Terrorist Attacks Impact Drinking** (with S. Sattler) *Analyses of Social Issues and Public Policy*, 24(1), 1-20. \[[PDF](Pradel_Sattler_Health_consequences_of_a_death_threat.pdf)\] \| \[[DOI](https://doi.org/10.1111/asap.12375)\]

**2022**

-   **Memories of a Death Threat: Negative Consequences of Unconscious Thoughts About a Terrorist Attack on Attitudes Towards Alcohol** (with S. Sattler) *OMEGA - Journal of Death and Dying*, 86(2), 668-687. \[[DOI](https://doi.org/10.1177/0030222820984935)\]

**2021**

-   **Biased Representation of Politicians in Google and Wikipedia Search?** *Political Communication*, 38(4), 447-478. \[[DOI](https://doi.org/10.1080/10584609.2020.1793846)\]

**2019**

-   **As the Tweet, so the Reply? Gender Bias in Digital Communication with Politicians** (with A. Mertens, A. Rozyjumayeva, J. Wäckerle) *Proceedings of the 10th ACM Conference on Web Science*. (Best Paper Award) \[[PDF](Mertens_Pradel_Rozyjumayeva_Waeckerle_As_the_Tweet_So_The_Reply.pdf)\] \| \[[DOI](https://doi.org/10.1145/3292522.3326013)\]

------------------------------------------------------------------------

## Book Chapters

-   **The Influence of Search Engines on Political Opinion Formation** (2026, Forthcoming) In: *Digital Society*, edited by M. Anastasiadis & C. Thimm.

-   **Scraping and Dictionary-Based Analysis of Politicians' Wikipedia Articles** (2025) In: *Quantitative Text Analysis Using R*, edited by J. Bernauer & A. Wohlmann. SAGE.
